### ISSUE TITLE
Could you maybe help me with making prettier do something against its normal behavior?

### ISSUE THREAD

**Issue by Evertt** [azz/prettier-transform#5]
I apologize if this may not have anything to do with your repository. I'm just stuck and seeing this repo I thought that you probably understand prettier way more than I do. You see, I am using `eslint` with `eslint-plugin-import` to define a very specific way that I'd like to sort my imports. It looks like this:

```js
{
  rules: {
    "import/order": [
      "error",
      {
        groups: [
          "type",
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
        ],
        pathGroups: [
          {
            pattern: "@/**",
            group: "internal",
          },
        ],
        alphabetize: {
          order: "asc",
        },
      },
    ],
  }
}
```

But of course it doesn't work, because prettier has its own ideas about how to order imports and it doesn't offer a configuration option to turn that off. So in the end, prettier reorders the imports according to its own philosophy.

I was wondering if you could maybe teach me how to write a plugin that turns that feature of prettier off. I can imagine that teaching me from beginning to end would take you more time than you're happy to invest. But if you can just give me a few pointers, I would already be super grateful! 🙏

**Comment by j-f1** [comment]
I'm pretty sure that Prettier never reorders anything, can you try running it from the terminal to see whether the issue still happens?

**Comment by Evertt** [comment]
Lol, yeah it was totally my mistake. I had forgotten that I had installed a plugin for prettier specifically to make it order imports. I was looking at a few plugins simultaneously, and well, that's what you get for it haha.
